"""
The ambient will be governed by two fields, the classical
electric field and the scalar field. 
"""

from __init__ import *
from dataclasses import dataclass


@dataclass
class Scalar_Field(Space):
    """
    The properties of the scalar field in question:
    Parameters:
        mass: The mass in natural units 
        charge: Charge in mass units (since 1+1 dimensions)

    Properties:
        z: the space [0, 1] considered
        field: the field at each point z
        deriv: the derivative wrt z of the field
    """
    mass: float
    charge: float
    #Implement here Robin boundary conditions? 
    value: np.ndarray
    n_points: int=50
    z: np.linspace(0, 1, n_points)
    
    def __add__(self, other_field):
        assert self.mass == other_field.mass
        assert self.charge == other_field.charge
        assert self.n_points == other_field.n_points

        return Scalar_Field(mass=self.mass,
                charge=self.charge,
                n_points=self.n_points,
                value=self.value + other_field.value)



@dataclass
class Ambient(Space):
    #As of meeting 15.11.23, note that the electric field 
    #will be generated by some charges outside of the 
    #space we are considering. This means that independently
    #of whatever happens inside the region z \in [0, 1], the 
    #electric field MUST be continuous and thus equal to 
    #some fixed value on the boundaries.
    pass

