from math_objects.fields import Field, Vector_Potential
from math_objects.value_generator import value_generator
from math_objects.iterable_output import iterable_output
from math_objects.unique_floats import unique_floats, float_in_array
from math_objects.savitzky_golay import savitzky_golay

import matplotlib.pyplot as plt
import numpy as np
import scipy as sp

class System:
    """The system that we are considering. This class
    is the final calculation, in the sense that after doing
    each calculation such as calculating the resulting
    scalar field and calculating its resulting electric field
    it calculates the converged electric field.

    Parameters:
        scalar_mass: float = 1      #The mass of the scalar field
        scalar_charge: float = 1    #The charge of the scalar field
        n_points: int = 100         #The nodes to be considered
        scalar_name: str = 'phi'    #The name of the field, for plotting reasons
        scalar_value: np.ndarray = 1#Initial guess for the value of the scalar field
                                    #If scalar, then it is just a repetition of that scalar.
        field_strength: float = 1    #The (external) electric field strength to which our system
                                    #is subject to.
    Properties:
        eigenstates: The eigenstates to a certain electric potential
    """

    # Since the integro differential equations are coupled,
    # I want a System in which the properties of the fields
    # are shared.
    # Relevant equations:
    # PDE for the scalar field coupled to a classical external electromagnetic potential
    # (del_t^2 - del_0^2 + 2 i e A0 del_t - e²A_0²)phi = 0
    # The solution phi to this PDE is going to yield a  certain charge density rho
    # rho = ie ( phi* (del_t + i e A0) phi - phi (del_t - i e A0) phi*)
    # Where phi* is the complex conjugate of phi
    # But the field is generated by the rho in the following manner:
    # A = -E(z-1/2) - \int_0^z \int_0^z' rho(z'') dz'' dz'
    # So the electric potential depends on the field and the
    # field depends on the potentia
    # So the electric potential depends on the field and the
    # field depends on the potential
    # NOTE: int f(x) dx = F(x) + c
    #   => Choose C such that A(0) is ALWAYS the same
    # Always = after each iteration to calculate the 'true' resultant field
    def __init__(
        self,
        lambda_value: float,
        scalar_mass: float,
        scalar_charge: float,
        A0_value: np.ndarray=None,
        n_points=100,
        scalar_name: str = "phi1",
        scalar_value: np.ndarray = 1,
        charge_density: np.ndarray=None
    ):
        self.lambda_value = lambda_value
        self.scalar_mass = scalar_mass
        self.scalar_charge = scalar_charge
        self.n_points = n_points
        self.scalar_name = scalar_name
        self.scalar_value = scalar_value
        self.charge_density = charge_density

        self.z = np.linspace(0, 1, n_points)

        self.phi = Field(
            value=self.scalar_value,
            charge=self.scalar_charge,
            mass=self.scalar_mass,
            n_points=self.n_points,
            name=scalar_name,
        )

        self._eigenstates = None

        if A0_value is None:
            # We are in the first iteration therefore A0 is the base EM field 
            self.A0_value = - lambda_value *  (self.z - 1/2)
        else:
            self.A0_value =  A0_value  # it is already the electromagnetic potential
        self.A_field_base = - lambda_value *  (self.z - 1/2)
#
#        except TypeError:
#            # field_strength was not a callable. is it an array?
#            try:
#                self.lambda_value = -2 * np.abs(field_strength[0]) # Also checks if callable
#                self.A0_value = (
#                    field_strength  # it is already the electromagnetic potential
#                )
#                self.A_field_base = -self.lambda_value * (self.z - 1 / 2)
#            except TypeError: # is neither callable nor array
#                self.lambda_value = field_strength
#                self.A_field_base = -field_strength * (self.z - 1 / 2)
#                self.A0_value = -field_strength * (self.z - 1 / 2)

        self.A0 = Vector_Potential(value=self.A0_value, n_points=self.n_points)

    from math_objects.Klein_Gordon import differential_equation, neumann_boundary_conditions, dirichlet_boundary_conditions
    #To calculate the eigenstates array:
    from math_objects.calculate_N_eigenstates import calculate_N_eigenstates 
    #For each eigenstate, to calculate its charge density
    from math_objects.calculate_charge_density import calculate_charge_density
    #To sum over all charge_densities
    from math_objects.calculate_total_charge_density import calculate_total_charge_density
    #To calculate the corresponding electric field
    from math_objects.new_electric_field import new_electric_field
    #And its electric potential
    from math_objects.modify_A0 import modify_A0

    #The final step of the iteration, to return the new state
    def one_iteration(self,
            omega_initial,
            omega_final,
            n_of_solutions
            ):
        """
        Parameters:
            n_of_solutions: int .how many eigenstates are wanted
            omega_initial: int. initial value to guess for omega
            omega_final: int. final value to guess for omega
            keep_omegas: False, Whether an output of the eigenvalues is given
        Returns: 
            System class
                        
        Iterates once the process of calculating the solution. In summary:
            1. calculates n_of_solutions eigenstates with eigenvalues in between omega_initial and omega_final.
            2. calculates the corresponding charge density as a function of z
            3. calculates the corresponding electric potential.
            4. returns 
                system = System(
                    scalar_name="phi",
                    n_points=self.n_points,
                    scalar_charge=self.scalar_charge,
                    scalar_value=self.scalar_value,
                    field_strength=new_A0,
                    scalar_mass=scalar_mass,
                )
        """
        eigenstate_array = self.calculate_N_eigenstates(
            omega_initial, omega_final, n_of_solutions
        )

        total_charge_density_callable = self.calculate_total_charge_density(eigenstate_array)
        total_charge_density_array = total_charge_density_callable(self.z)
        total_charge_density_array[0] = 0

        smoothed_charge_density = savitzky_golay(
            total_charge_density_array, 40*self.n_points // (n_of_solutions + 1), 2
        )
        #smoothed_charge_density = savitzky_golay(
        #    smoothed_charge_density, 10*self.n_points // (n_of_solutions + 1), 4
        #)
        perturbation_A0 = self.modify_A0(smoothed_charge_density).y[0]

        return System(
                    lambda_value=self.lambda_value, 
                    scalar_name="phi",
                    n_points=self.n_points,
                    scalar_charge=self.scalar_charge,
                    scalar_value=self.scalar_value,
                    A0_value=perturbation_A0 + self.A_field_base,
                    scalar_mass=self.scalar_mass,
                    charge_density=smoothed_charge_density
                    )
