from math_objects.fields import Field, Vector_Potential
from math_objects.value_generator import value_generator
from math_objects.unique_floats import unique_floats, float_in_array
from math_objects.Klein_Gordon import Klein_Gordon

import matplotlib.pyplot as plt
import numpy as np
import scipy as sp

class System(Klein_Gordon):
    """The system that we are considering. This class 
    is the final calculation, in the sense that after doing
    each calculation such as calculating the resulting
    scalar field and calculating its resulting electric field
    it calculates the converged electric field.

    Parameters:
        scalar_mass: float = 1      #The mass of the scalar field
        scalar_charge: float = 1    #The charge of the scalar field
        n_points: int = 100         #The nodes to be considered   
        scalar_name: str = 'phi'    #The name of the field, for plotting reasons
        scalar_value: np.ndarray = 1#Initial guess for the value of the scalar field
                                    #If scalar, then it is just a repetition of that scalar.
        field_strength: float = 1    #The (external) electric field strength to which our system
                                    #is subject to. 
    Properties:
        eigenstates: The eigenstates to a certain electric potential
    """
    #Since the integro differential equations are coupled,
    #I want a System in which the properties of the fields
    #are shared. 
    #Relevant equations:
    #PDE for the scalar field coupled to a classical external electromagnetic potential
    #(del_t^2 - del_0^2 + 2 i e A0 del_t - e²A_0²)phi = 0
    #The solution phi to this PDE is going to yield a  certain charge density rho
    #rho = ie ( phi* (del_t + i e A0) phi - phi (del_t - i e A0) phi*)
    #Where phi* is the complex conjugate of phi
    #But the field is generated by the rho in the following manner:
    #A = -E(z-1/2) - \int_0^z \int_0^z' rho(z'') dz'' dz'
    #So the electric potential depends on the field and the
    #field depends on the potentia
    #So the electric potential depends on the field and the
    #field depends on the potential
    #NOTE: int f(x) dx = F(x) + c
    #   => Choose C such that A(0) is ALWAYS the same
    #Always = after each iteration to calculate the 'true' resultant field
    def __init__(self, 
        field_strength,
        scalar_mass: float,
        scalar_charge: float,
        n_points = 100,
        scalar_name: str='phi1',
        scalar_value: np.ndarray=1):

            self.scalar_mass = scalar_mass
            self.scalar_charge = scalar_charge
            self.n_points = n_points
            self.scalar_name = scalar_name
            self.scalar_value = scalar_value

            self.z = np.linspace(0, 1, n_points)

            self.phi = Field(value=self.scalar_value, 
                    charge=self.scalar_charge, 
                    mass=self.scalar_mass, 
                    n_points=self.n_points,
                    name=scalar_name)

            self._eigenstates = None

            try:
                field_strength(0) #field_strength is callable, therefoere
                self.A_field_base = field_strength #it is already the electromagnetic potential
            except TypeError:
                #field_strength is only the lambda factor. we are in the first iteration
                self.A_field_base = - field_strength * (self.z - 1/2)

            self.A0 = Vector_Potential(value=self.A_field_base,
                    n_points=self.n_points)


    def calculate_N_eigenstates(self, 
                              N: int,
                              omega_in: float,
                              omega_end: float,
                              boundary_conditions = None,
                              tolerance: float=1e-2, 
                              n_points: int=300, 
                              max_nodes: int=3000):
        """Calculates N  KG eigenstates associated to a certain external classical field
        Parameters
            N: int,
                Amount of desired eigenstates. 
            omega_in: float,
                initial omega for the sweep of eigenvalue
            omega_end: float,
                final omega for the sweep of eigenvalue
            boundary_conditions: float=None,
                boundary conditions tos solve the differential equation. 
                If not given (None), they are assumed to be dirichlet (y(0) = y(1) = 0)
            tolerance: float=1e-2, 
                The tolerance to check wether the solution converged
            n_points: int=300, 
                Number of nodes in the solution
            scalar_name: str='phi'
                Name of the scalar field. For representation purposes
            max_nodes: int=3000
                Maximum number of nodes for a given solution 
        Returns:
            [scipy.integrate.solve_bvp.solution] of len() = N
        
        """
        if omega_in > 0:
            print("Warning: The starting value for the omega guesses is positive, and the solution needs negative frequency solutions")

        if boundary_conditions is None:
            boundary_conditions = self.dirichlet_boundary_conditions

        solution_array = []

        for i, omega_guess in enumerate(np.linspace(omega_in, omega_end, N)):
            solution = sp.integrate.solve_bvp(self.differential_equation,
                    boundary_conditions, 
                    self.z, 
                    (self.phi.value, self.phi.gradient.value),
                    p=(omega_guess, ),
                    verbose=0,
                    max_nodes=max_nodes,
                    tol=tolerance)

            solution_array.append(solution)

        return solution_array

    def first_N_eigenstates(self, 
                            n,
                            omega_0_guess=0,
                            omega_ratio=1e-2,
                            method='linear',
                            tol=1e-2,
                            boundary_conditions='dirichlet'):
        """
        Calculates the first n eigenstates of the system and its energies
        Parameters:
            n: number of desired eigenstates
            omega_0_guess: guess for the frequency of the 
            boundary_conditions: dirichlet or neumann 
            tol: 
        Returns:
            eigenstates: [sol1, ...] a 1xn array of scipy.integrate.solve_bvp solution objects
        """

        #bcs = self.boundary_conditions[boundary_conditions]
        omega_array = []
        eigenstates = []
        for i, omega_guess in enumerate(value_generator(omega_0_guess, omega_ratio, method=method)):
            #print('Estoy en el intento n', i, 'Omega_guess =', omega_guess)
            solution = sp.integrate.solve_bvp(self.differential_equation,
                    self.dirichlet_boundary_conditions,
                    #self.dirichlet_boundary_conditions,
                    self.z, 
                    (self.phi.value, self.phi.gradient.value),
                    p=(omega_guess, ),
                    tol=tol)

            omega_solution = solution.p[0]
            if float_in_array(omega_solution, omega_array, tol=tol):
                continue
            else:
                omega_array.append(omega_solution)
                eigenstates.append(solution)

            if len(omega_array) >= n:
                break
        return eigenstates

    def calculate_total_charge_density(self, eigenstates):
        """
        Calculates the charge density in the system given a certain family of solutions
        Parameters:
            z: float the z value at which the charge density is being calculated
            eigenstates: [scipy.integrate.solve_bvp solution objects]
        Returns: 
            charge_density: float, the charge density at z
        """

        total_charge_density = 0.

        for i, solution in enumerate(eigenstates):
            omega_n = solution.p[0]
            phi = solution.sol(self.z)[0]
            field_factor = (omega_n - self.phi.charge * self.A0(self.z))*np.sign(omega_n)
            solution_squared = lambda z: (solution.p[0] - self.phi.charge * self.A0(z))*np.real(solution.sol(z)[0]**2)
            solution_norm_squared = sp.integrate.quad(solution_squared, 0, 1)[0]
            charge_density_n = field_factor*np.real(solution.sol(self.z)[0])**2/self.phi.mass/solution_norm_squared

            total_charge_density += charge_density_n

        return total_charge_density 

    def new_electric_field(self, z, eigenstates):
        """
        Calculates the corresponding electric field to a certain charge density
        Parameters:
            z: float. The z value at which the electric field is to be calculated
            eigenstates: SolutionArray. A given solution array to calculate_charge_density
        Returns:
            electric_field: float, the electric field at z
            """
     
        charge_density_at_z = lambda z, eigenstates: self.calculate_charge_density(z, eigenstates)     
        modified_electric = sp.integrate.quad(charge_density, 0, z, args=eigenstates) 
         
        return modified_electric 

    def new_vector_field(self, z, eigenstates):
        """
        Calculates the new vector field A0 corresponding to a family of solutions to the previous one
        Parameters:
            z: float. The z value at which A0 field is to be calculated
            eigenstates: SolutionArray. A given solution array to calculate_charge_density
        Returns:
            new_vector_field: float, the electromagnetic field at z
        """
        electric_field_at_z = lambda z, eigenstates: self.new_electric_field(z, eigenstates)
        modified_vector_field = -sp.integrate.quad(electric_field_at_z, 0, z, args=eigenstates) - self.field_strength * (z-1/2)

        return modified_vector_field
