from math_objects.fields import Field, Vector_Potential
from math_objects.value_generator import value_generator
from math_objects.iterable_output import iterable_output 
from math_objects.unique_floats import unique_floats, float_in_array
from math_objects.Klein_Gordon import Klein_Gordon

import matplotlib.pyplot as plt
import numpy as np
import scipy as sp

class System(Klein_Gordon):
    """The system that we are considering. This class 
    is the final calculation, in the sense that after doing
    each calculation such as calculating the resulting
    scalar field and calculating its resulting electric field
    it calculates the converged electric field.

    Parameters:
        scalar_mass: float = 1      #The mass of the scalar field
        scalar_charge: float = 1    #The charge of the scalar field
        n_points: int = 100         #The nodes to be considered   
        scalar_name: str = 'phi'    #The name of the field, for plotting reasons
        scalar_value: np.ndarray = 1#Initial guess for the value of the scalar field
                                    #If scalar, then it is just a repetition of that scalar.
        field_strength: float = 1    #The (external) electric field strength to which our system
                                    #is subject to. 
    Properties:
        eigenstates: The eigenstates to a certain electric potential
    """
    #Since the integro differential equations are coupled,
    #I want a System in which the properties of the fields
    #are shared. 
    #Relevant equations:
    #PDE for the scalar field coupled to a classical external electromagnetic potential
    #(del_t^2 - del_0^2 + 2 i e A0 del_t - e²A_0²)phi = 0
    #The solution phi to this PDE is going to yield a  certain charge density rho
    #rho = ie ( phi* (del_t + i e A0) phi - phi (del_t - i e A0) phi*)
    #Where phi* is the complex conjugate of phi
    #But the field is generated by the rho in the following manner:
    #A = -E(z-1/2) - \int_0^z \int_0^z' rho(z'') dz'' dz'
    #So the electric potential depends on the field and the
    #field depends on the potentia
    #So the electric potential depends on the field and the
    #field depends on the potential
    #NOTE: int f(x) dx = F(x) + c
    #   => Choose C such that A(0) is ALWAYS the same
    #Always = after each iteration to calculate the 'true' resultant field
    def __init__(self, 
        field_strength,
        scalar_mass: float,
        scalar_charge: float,
        n_points = 100,
        scalar_name: str='phi1',
        scalar_value: np.ndarray=1):

            self.scalar_mass = scalar_mass
            self.scalar_charge = scalar_charge
            self.n_points = n_points
            self.scalar_name = scalar_name
            self.scalar_value = scalar_value

            self.z = np.linspace(0, 1, n_points)

            self.phi = Field(value=self.scalar_value, 
                    charge=self.scalar_charge, 
                    mass=self.scalar_mass, 
                    n_points=self.n_points,
                    name=scalar_name)

            self._eigenstates = None

            try:
                field_strength(0) #field_strength is callable, therefoere
                self.A_field_base = field_strength #it is already the electromagnetic potential
            except TypeError:
                #field_strength is only the lambda factor. we are in the first iteration
                self.A_field_base = - field_strength * (self.z - 1/2)

            self.A0 = Vector_Potential(value=self.A_field_base,
                    n_points=self.n_points)


    def calculate_N_eigenstates(self, 
                              N: int,
                              omega_in: float,
                              omega_end: float,
                              boundary_conditions = None,
                              tolerance: float=1e-2, 
                              n_points: int=300, 
                              max_nodes: int=3000):
        """Calculates N (not necessarily normalized) KG eigenstates associated to a certain external classical field
        Parameters
            N: int,
                Amount of desired eigenstates. 
            omega_in: float,
                initial omega for the sweep of eigenvalue
            omega_end: float,
                final omega for the sweep of eigenvalue
            boundary_conditions: float=None,
                boundary conditions tos solve the differential equation. 
                If not given (None), they are assumed to be dirichlet (y(0) = y(1) = 0)
            tolerance: float=1e-2, 
                The tolerance to check wether the solution converged
            n_points: int=300, 
                Number of nodes in the solution
            scalar_name: str='phi'
                Name of the scalar field. For representation purposes
            max_nodes: int=3000
                Maximum number of nodes for a given solution 
        Returns:
            [scipy.integrate.solve_bvp.solution] of len() = N
        
        """
        if omega_in > 0:
            print("Warning: The starting value for the omega guesses is positive, and the solution needs negative frequency solutions")

        if boundary_conditions is None:
            boundary_conditions = self.dirichlet_boundary_conditions

        solution_array = []

        for i, omega_guess in enumerate(np.linspace(omega_in, omega_end, N)):

            guess = np.sin(omega_guess*self.z)
            guess_derivative = np.diff(guess)
            guess_derivative = np.append(guess_derivative, guess_derivative[-1])

            solution = sp.integrate.solve_bvp(self.differential_equation,
                    boundary_conditions, 
                    self.z, 
                    (guess, guess_derivative),
                    p=(omega_guess, ),
                    verbose=0,
                    max_nodes=max_nodes,
                    tol=tolerance)

            if solution.success:
                solution_array.append(solution)

        return solution_array

    def calculate_charge_density(self, solution):
        """
        Calculates the charge density associated to certain eigenstate
        Parameters:
            eigenstates: scipy.integrate.solve_bvp solution object
        Returns: 
            charge_density: callable, the charge density corresponding to the input eigenstate
        """

        eigenvalue = solution.p[0]
        charge_density_no_normalization = lambda z: (eigenvalue - self.phi.charge * self.A0(z))*np.real(solution.sol(z)[0]**2)
        charge_density_norm_squared = sp.integrate.quad(charge_density_no_normalization, 0, 1)[0]
        charge_density_normalized = lambda z: np.sign(eigenvalue)*charge_density_no_normalization(z)/charge_density_norm_squared

        return charge_density_normalized

    def calculate_total_charge_density(self, eigenstate_array):
        """
        Calculates the charge density in the system given a certain family of solutions
        Parameters:
            eigenstate_array: [scipy.integrate.solve_bvp solution objects]
        Returns: 
            charge_density: np.array([float]) The total charge density at every node
        """

        def total_charge_density(z):
            total_charge_density = 0

            for i, solution in enumerate(eigenstate_array):
                total_charge_density = total_charge_density + self.calculate_charge_density(solution)(z)

            return total_charge_density 

        return total_charge_density


    def new_electric_field(self, eigenstate_array):
        """
        Calculates the corresponding electric field to a certain charge density
        Parameters:
            z: float. The z value at which the electric field is to be calculated
            eigenstate_array: SolutionArray. A given solution array to calculate_charge_density
        Returns:
            electric_field: float, the electric field at z
            """
     
        #Calculate this solving an ODE, not integration
        print('I am again here, hello!')
        charge_density_at_z = self.calculate_total_charge_density(eigenstate_array)
        
        modified_electric = sp.integrate.solve_ivp(lambda z, y: charge_density_at_z(z),
                y0 = [0],
                t_span=(self.z[0], self.z[-1]),
                t_eval=self.z)
        print('The ODE was completed!')

        return modified_electric 

    def new_vector_field(self, eigenstate_array):
        """
        Calculates the new vector field A0 corresponding to a family of solutions to the previous one
        Parameters:
            z: float. The z value at which A0 field is to be calculated
            eigenstate_array: SolutionArray. A given solution array to calculate_charge_density
        Returns:
            new_vector_field: float, the electromagnetic field at z
        """
        #Calculate this solving an ODE, not integrating
        charge_density_at_z = self.calculate_total_charge_density(eigenstate_array)

        def dAdz(z, A):
            return np.array(A[1], -charge_density_at_z(z))

        modified_electric = sp.integrate.solve_ivp(dAdz, 
                y0 = [0,1],
                t_span=(self.z[0], self.z[-1]),
                t_eval=self.z )

        return modified_electric
