from math_objects.fields import Field, Vector_Potential
from math_objects.value_generator import value_generator
from math_objects.iterable_output import iterable_output
from math_objects.unique_floats import unique_floats, float_in_array
from math_objects.savitzky_golay import savitzky_golay
from math_objects.Klein_Gordon import Klein_Gordon

import matplotlib.pyplot as plt
import numpy as np
import scipy as sp

class System(Klein_Gordon):
    """The system that we are considering. This class
    is the final calculation, in the sense that after doing
    each calculation such as calculating the resulting
    scalar field and calculating its resulting electric field
    it calculates the converged electric field.

    Parameters:
        scalar_mass: float = 1      #The mass of the scalar field
        scalar_charge: float = 1    #The charge of the scalar field
        n_points: int = 100         #The nodes to be considered
        scalar_name: str = 'phi'    #The name of the field, for plotting reasons
        scalar_value: np.ndarray = 1#Initial guess for the value of the scalar field
                                    #If scalar, then it is just a repetition of that scalar.
        field_strength: float = 1    #The (external) electric field strength to which our system
                                    #is subject to.
        self.eigenstates: [solve_bvp.solutions] # Array of solutions from a previous calculation
    Properties:
        eigenstates: The eigenstates to a certain electric potential
    """

    # Since the integro differential equations are coupled,
    # I want a System in which the properties of the fields
    # are shared.
    # Relevant equations:
    # PDE for the scalar field coupled to a classical external electromagnetic potential
    # (del_t^2 - del_0^2 + 2 i e A0 del_t - e²A_0²)phi = 0
    # The solution phi to this PDE is going to yield a  certain charge density rho
    # rho = ie ( phi* (del_t + i e A0) phi - phi (del_t - i e A0) phi*)
    # Where phi* is the complex conjugate of phi
    # But the field is generated by the rho in the following manner:
    # A = -E(z-1/2) - \int_0^z \int_0^z' rho(z'') dz'' dz'
    # So the electric potential depends on the field and the
    # field depends on the potentia
    # So the electric potential depends on the field and the
    # field depends on the potential
    # NOTE: int f(x) dx = F(x) + c
    #   => Choose C such that A(0) is ALWAYS the same
    # Always = after each iteration to calculate the 'true' resultant field
    def __init__(
        self,
        field_strength,
        scalar_mass: float,
        scalar_charge: float,
        n_points=100,
        scalar_name: str = "phi1",
        scalar_value: np.ndarray = 1,
        eigenstates: [float]=None
    ):
        self.scalar_mass = scalar_mass
        self.scalar_charge = scalar_charge
        self.n_points = n_points
        self.scalar_name = scalar_name
        self.scalar_value = scalar_value
        self.eigenstates = eigenstates 

        self.z = np.linspace(0, 1, n_points)

        self.phi = Field(
            value=self.scalar_value,
            charge=self.scalar_charge,
            mass=self.scalar_mass,
            n_points=self.n_points,
            name=scalar_name,
        )

        self._eigenstates = None

        try:
            # Since A0(z) = - λ (z-1/2) then  λ = 2*A0(0)
            self.lambda_value = -2 * field_strength(
                0
            )  
            # Tread carefully since this above has to be imposed by hand
            self.A_field_base = (
                field_strength  # it is already the electromagnetic potential
            )
        except TypeError:
            # field_strength is only the lambda factor. we are in the first iteration
            self.lambda_value = field_strength
            self.A_field_base = -field_strength * (self.z - 1 / 2)

        self.A0 = Vector_Potential(value=self.A_field_base, n_points=self.n_points)

    def calculate_N_eigenstates(
        self,
        *args,
        boundary_conditions=None,
        tolerance: float = 1e-2,
        n_points: int = 300,
        max_nodes: int = 3000,
        tol: float= 1e-1
    ):
        """Calculates N (not necessarily normalized) KG eigenstates associated to a certain external classical field
        Parameters
            N: int,
                Amount of desired eigenstates.
            omega_in: float,
                initial omega for the sweep of eigenvalue
            omega_end: float,
                final omega for the sweep of eigenvalue
            boundary_conditions: float=None,
                boundary conditions tos solve the differential equation.
                If not given (None), they are assumed to be dirichlet (y(0) = y(1) = 0)
            tolerance: float=1e-2,
                The tolerance to check wether the solution converged
            n_points: int=300,
                Number of nodes in the solution
            scalar_name: str='phi'
                Name of the scalar field. For representation purposes
            max_nodes: int=3000
                Maximum number of nodes for a given solution
        Returns:
            [scipy.integrate.solve_bvp.solution] of len() = N

        """
        if not self.eigenstates is None:
            omega_guess_array = [solution.p[0] for solution in self.eigenstates]
        else:
            try:
                omega_in, omega_end, N = args
                if omega_in > 0:
                    print(
                        "Warning: The starting value for the omega guesses is positive, and the solution needs negative frequency solutions"
                    )
                n_value_array = np.linspace(omega_in, omega_end, N)

                # Massive perturbative case:
                # omega_n = sign(n) * sqrt(n² pi² + m²)
                omega_guess_array = (
                        np.sign(n_value_array) *
                        np.sqrt(
                            n_value_array**2 * np.pi **2 
                            + self.scalar_mass**2
                            )
                        ) 
                        

            except ValueError:
                raise ValueError("There was no input omega_in, omega_end and N, and self.eigenstates=None.")

        if boundary_conditions is None:
            boundary_conditions = self.dirichlet_boundary_conditions

        solution_array = []
        eigenvalue_solution_array = []

        print(f'omega_in={omega_in}, omega_end={omega_end}, N={N}')

        repeated_count = 0
        for omega_guess in omega_guess_array:
            # print("Input previous solutions as new guesses")
            # Guessing the solution of the ODE
            eigenfunction_guess = np.sin( 
                omega_guess * self.z
            )  
            guess_derivative = np.diff(eigenfunction_guess)
            guess_derivative = np.append(
                guess_derivative, guess_derivative[-1]
            )  # since calculating derivatives removes the last point

            solution = sp.integrate.solve_bvp(
                self.differential_equation,
                boundary_conditions,
                self.z,
                (eigenfunction_guess, guess_derivative),
                p=(omega_guess,),
                verbose=0,
                max_nodes=max_nodes,
                tol=tolerance,
            )

            omega_n = solution.p[0]
            if float_in_array(omega_n, eigenvalue_solution_array, tol=tol):
                #print("Found a repeated eigenvalue!")
                repeated_count += 1
                continue
            if solution.success:  # If it converged, add it to the solutions array
                eigenvalue_solution_array.append(omega_n)
                solution_array.append(solution)

        print(f'Found {repeated_count} repeated eigenvalues')

        return solution_array

    def calculate_charge_density(self, solution, integration_limit = 200):
        """
        Calculates the charge density associated to certain eigenstate
        Parameters:
            eigenstates: scipy.integrate.solve_bvp solution object
            integration_limit: float = 200. The integration limit for scipy.integrate.quad
        Returns:
            charge_density: callable, the charge density corresponding to the input eigenstate
        """

        eigenvalue = solution.p[0]
        charge_density_without_normalization = lambda z: (
            eigenvalue - self.phi.charge * self.A0(z)
        ) * np.real(solution.sol(z)[0] ** 2)
        charge_density_norm_squared = sp.integrate.quad(
            charge_density_without_normalization, 0, 1,
            limit=integration_limit
        )[0]
        charge_density_normalized = (
            lambda z: charge_density_without_normalization(z)
            / charge_density_norm_squared
        )

        return charge_density_normalized

    def calculate_total_charge_density(self, eigenstate_array):
        """
        Calculates the charge density in the system given a certain family of solutions
        Parameters:
            eigenstate_array: [scipy.integrate.solve_bvp solution objects]
        Returns:
            charge_density: np.array([float]) The total charge density at every node
        """
        e = self.phi.charge

        def total_charge_density(z):
            total_charge_density = 0
            cutoff_N = len(eigenstate_array) // 2
            for i, solution in enumerate(eigenstate_array):
                n = np.abs(i - cutoff_N)
                # we are adding and substracting the series -2eλ lim(t -> 0) sum z(1-z) sin(pi n z) cos (pi n z) exp(i pi n(t + i epsilon)) = -eλ z(1-z)/2 cot(pi z)
                # This way we can make the cutoff earlier, since each of the terms in the series will go to 0 faster.
                renormalization_term = (
                    e
                    * self.lambda_value
                    * z
                    * (1 - z)
                    * np.sin(np.pi * n * z)
                    * np.cos(np.pi * n * z)
                )
                renormalization_term = savitzky_golay(
                         renormalization_term,
                         51,
                         1
                         )
                tau = 0.001 # For the point split renormalization scheme, we
                           # take the limit of tau going to 0
                damping_factor = np.exp(-1j * np.abs(solution.p[0])*(tau+1j*tau))
                adding_term = 1 # To add or remove renormalization at desire
                total_charge_density = (
                    total_charge_density
                    + np.sign(solution.p[0]) * (
                        self.calculate_charge_density(solution)(z)
                    + adding_term*renormalization_term)*damping_factor
                )

            massless_charge_density = (
                e * self.lambda_value * z * (1 - z) / 4 / np.tan(np.pi * z)
            )
            potential_term = 1/np.pi * e**2 * self.A0(z) # Extra term coming from point-split renormalization
            return - (
                    -total_charge_density 
                    + adding_term * massless_charge_density 
                    - potential_term
                    )

        return total_charge_density

    def new_electric_field(self, eigenstate_array):
        """
        Calculates the corresponding electric field to a certain charge density
        Parameters:
            z: float. The z value at which the electric field is to be calculated
            eigenstate_array: SolutionArray. A given solution array to calculate_charge_density
        Returns:
            electric_field: float, the electric field at z
        """

        # Calculate this solving an ODE, not integration
        charge_density_at_z = self.calculate_total_charge_density(eigenstate_array)

        modified_electric = sp.integrate.solve_ivp(
            lambda z, y: charge_density_at_z(z),
            y0=[0],
            t_span=(self.z[0], self.z[-1]),
            t_eval=self.z,
        )
        print("The ODE was completed!")

        return modified_electric

    def new_vector_field(self, charge_density):
        """
        Calculates the new vector field A0 corresponding to a family of solutions to the previous one
        Parameters:
            charge_density
        Returns:
            new_vector_field: callable, the electromagnetic field at z
        """
        # Calculate this solving an ODE, not integrating

        try:
            iter(charge_density) # Checking if charge_density is array
            charge_density = sp.interpolate.CubicSpline(self.z, charge_density)
        except TypeError:
            try:
                charge_density(0.5) # Check if charge_density is callable. 0.5 must be in the accepted values
                                    # if callable, do nothing
            except TypeError:
                raise TypeError("charge_density should be either iterable or callable")

        def dAdz(z, A):
            return [A[1], -charge_density(z)]

        def bc(Aa, Ab):	
            return [Aa[0], Ab[0]] # Since there should be no potential on the boundary.

        modified_electric = sp.integrate.solve_bvp(
            dAdz, bc, self.z, np.zeros((self.n_points, 2)).T
        )

        return modified_electric

    def one_iteration(self,
            omega_initial,
            omega_final,
            n_of_solutions
            ):
        """
        Parameters:
            n_of_solutions: int .how many eigenstates are wanted
            omega_initial: int. initial value to guess for omega
            omega_final: int. final value to guess for omega
            keep_omegas: False, Whether an output of the eigenvalues is given
        Returns: 
            System class
                    	
        Iterates once the process of calculating the solution. In summary:
            1. calculates n_of_solutions eigenstates with eigenvalues in between omega_initial and omega_final.
            2. calculates the corresponding charge density as a function of z
            3. calculates the corresponding electric potential.
            4. returns 
                system = System(
                    scalar_name="phi",
                    n_points=self.n_points,
                    scalar_charge=self.scalar_charge,
                    scalar_value=self.scalar_value,
                    field_strength=new_A0,
                    scalar_mass=scalar_mass,
                )
        """
        eigenstate_array = self.calculate_N_eigenstates(
            omega_initial, omega_final, n_of_solutions
        )

        total_charge_density_callable = self.calculate_total_charge_density(eigenstate_array)
        total_charge_density_array = total_charge_density_callable(self.z)
        total_charge_density_array = total_charge_density_array[0] 

        smoothed_charge_density = savitzky_golay(
            total_charge_density_array, 10*self.n_points // (n_of_solutions + 1), 2
        )
        #smoothed_charge_density = savitzky_golay(
        #    smoothed_charge_density, 10*self.n_points // (n_of_solutions + 1), 4
        #)
        new_A0 = self.new_vector_field(smoothed_charge_density)

        return System(
                    scalar_name="phi",
                    n_points=self.n_points,
                    scalar_charge=self.scalar_charge,
                    scalar_value=self.scalar_value,
                    field_strength=new_A0,
                    scalar_mass=self.scalar_mass,
                    )
